[workspace]
authors = ["claus-92 <claudio.santonastaso@gmail.com>"]
channels = ["conda-forge"]
name = "SAMDAQ"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = "mkdir -p build && cd build && cmake .. && make -j$(nproc)"
samdaq = "build/SAMDAQ"

[dependencies]
cmake = ">=3.10"
make = "*"
compilers = "*"
c-compiler = "*"
cxx-compiler = "*"
qt = "5.15.8.*"
root = "6.34.4.*"
python = "3.11.*"
jupyter = "*"
numpy = "*"
matplotlib = "3.7.*"
libgl-devel = ">=1.7.0,<2"
